# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear_vibes_app', '0003_auto_20160407_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='review_images')),
                ('caption1', models.CharField(blank=True, max_length=30, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='review_images')),
                ('caption2', models.CharField(blank=True, max_length=30, null=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='review_images')),
                ('caption3', models.CharField(blank=True, max_length=30, null=True)),
                ('image4', models.ImageField(blank=True, null=True, upload_to='review_images')),
                ('caption4', models.CharField(blank=True, max_length=30, null=True)),
                ('image5', models.ImageField(blank=True, null=True, upload_to='review_images')),
                ('caption5', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gear_vibes_app.Review'),
        ),
    ]
