# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_vibes_app', '0004_auto_20160407_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_name',
            field=models.CharField(default='test', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.CharField(choices=[('pho', 'Photography'), ('mus', 'Music Gear'), ('mob', 'Mobile Tech')], max_length=3),
        ),
    ]
