# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_vibes_app', '0005_auto_20160407_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gear_vibes_app.Tag'),
        ),
    ]
