# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear_vibes_app', '0006_auto_20160407_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='review_images')),
                ('caption', models.CharField(blank=True, max_length=30, null=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='featured_image',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear_vibes_app.Review'),
        ),
    ]
