# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_vibes_app', '0007_auto_20160408_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.CharField(choices=[('Photography', 'Photography'), ('Music Gear', 'Music Gear'), ('Mobile Tech', 'Mobile Tech')], max_length=30),
        ),
    ]
