# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear_vibes_app', '0013_auto_20160416_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='review',
            name='featured',
        ),
    ]
