# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_vibes_app', '0015_auto_20160419_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='intro',
            field=models.TextField(default='default values and stuff'),
            preserve_default=False,
        ),
    ]
