# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear_vibes_app', '0016_review_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='block_quote',
            field=models.CharField(max_length=200),
        ),
    ]
