# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms
import gear_vibes.custom_storages


class Migration(migrations.Migration):

    dependencies = [
        ('gear_vibes_app', '0017_auto_20160420_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=gear_vibes.custom_storages.MediaStorage(), upload_to='review_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=django_resized.forms.ResizedImageField(blank=True, null=True, storage=gear_vibes.custom_storages.MediaStorage(), upload_to='profile_images'),
        ),
    ]
