# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 20:20
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms
import gear_vibes.custom_storages


class Migration(migrations.Migration):

    dependencies = [
        ('gear_vibes_app', '0018_auto_20160509_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, null=True, storage=gear_vibes.custom_storages.MediaStorage(), upload_to='review_images'),
        ),
    ]
